image: "python:3.7"

#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

# different stages in the pipeline
stages:
  - Static Analysis
  - Test

#defines the job in Static Analysis
pylint:
  stage: Static Analysis
  script:
  - pylint src/