image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

pylint:
  stage: Static Analysis
  script:
  - pip install pylint
  - pylint src/

pytest:
  stage: Test
  script:
  - cd test/;PYTHONPATH=../src python -m unittest *_test.py
