image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test
  - Deploy

pylint:
  stage: Static Analysis
  script:
  - pip install pylint
  - pylint src/

pytest:
  stage: Test
  script:
  - pip install pytest
  - cd test/;pytest -v

pyinstaller:
  stage: Deploy
  script:
  - pip install pyinstaller
  - pyinstaller -F src/server.py
  tags:
  - deploy
  artifacts:
    paths:
      - dist/*.exe