image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test
  - Build

pylint:
  stage: Static Analysis
  script:
  - pip install pylint
  - pylint src/

pytest:
  stage: Test
  script:
  - pip install pytest
  - cd test/;pytest -v

#pyinstaller:
#  stage: Build
#  script:
#  - pip install pyinstaller
#  - pyinstaller -F -y src/server.py
#  artifacts:
#    paths:
#      - dist/server
