image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test
  - Deploy

pylint:
  stage: Static Analysis
  script:
  - pip install pylint
  - pylint ./src

unittest:
  stage: Test
  script:
  - cd test/;PYTHONPATH=../src python -m unittest *_test.py

pyinstaller:
  stage: Deploy
  script:
  - pip install pyinstaller
  - pyinstaller -F src/server.py
  tags:
  - deploy
  artifacts:
    paths:
      - ./dist/*.exe
