# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Static Analysis
        run : pylint ./src       

  unittest:
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
      - name: Test
        run: |
          python --version
          pip install -r requirements.txt
          cd test/;PYTHONPATH=../src python -m unittest *_test.py
